/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:1382743b-118f-4094-907b-670b8b43d9a8",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_0Q44YMkeU",
  aws_user_pools_web_client_id: "651dnltk7a4p0p1ko0pnpvml0g",
  oauth: {},
  aws_appsync_graphqlEndpoint:
    "https://yydzafx2djc5tnybwer6u2zqye.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_appsync_apiKey: "da2-xiehougbqncenpyfyh7dsh3zhe",
};

export default awsmobile;
